### DISCUSSION TITLE
Version 0.7.test

### DISCUSSION THREAD

**Discussion by urania-dev** [urania-dev/snapp#16] [Announcements]
Version 0.7.test is here.

It has major changes, so you may want to install it as a second instance, and if it works, report it on the repository :)

```YAML
version: "3"
services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - 6379:6379/tcp
      - 8001:8001
    volumes:
      - /home/snapp/redis/test:/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes"
  snapp:
    image: uraniadev/snapp:0.7.test
    ports:
      - 3000:3000
    volumes:
    - /home/snapp/test/db.sqlite:/app/prisma/db.sqlite # path to old SQLITE db
    #  - /home/snapp/app/translations:/app/translations:ro
    # - /home/snapp/redis/theme/theme.css:/app/static/custom-theme.css


    environment:
      AUTH_SECRET: {random-generated-string}
      DB_HOST: 
      DB_PASS:
      DB_PORT: 6379
      DB_IDX: 0
      ENABLE_LIMITS: false
      ENABLE_SIGNUP: true
      ENABLE_HOME: false
      DEFAULT_THEME: dark
      DEFAULT_LANG: en
      LOCALIZATION_FOLDER: /app/translations
      MAX_SHORT_URL: 10
      MAX_USAGES: 0
      MAX_RPM: 0
      MAX_RPD: 0
      VIRUSTOTAL_API_KEY: 
      PUBLIC_URL: https://example.com
      ORIGIN: https://example.com

```

**Comment by Hutch79** [comment]
Heya, 
Sorry for my inactivity ^^'

I just tried to set up a test deployment and struggled to create an initial account...
I set the signup to true, and restarted the container as well as the stack multiple times, but somehow it just doesn't like me XD
Thats my current stack:
```yaml
version: "3"
services:
  redis-stack:
    image: redis/redis-stack:latest
    #ports:  # Potential security risc, see below
    #  - 6379:6379/tcp
    #  - 8001:8001
    volumes:
      - /docker/snapp_test/redis/test:/data:rw
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes"
    networks:
      - snapp_test
      
  snapp:
    image: uraniadev/snapp:0.7.test
    container_name: snapp
    #volumes:
    #  - /docker/snapp_test/app/translations:/app/translations:ro
    #  - /docker/snapp_test/redis/theme/theme.css:/app/static/custom-theme.css

    environment:
      AUTH_SECRET: NopeThisIsMySecret!
      DB_HOST: redis-stack
      # DB_PASS: # Optional: Requires `--requirepass mypassword` in REDIS_ARGS
      DB_PORT: 6379
      DB_IDX: 0
      ENABLE_LIMITS: false
      ENABLE_SIGNUP: true
      ENABLE_HOME: true
      DEFAULT_THEME: dark
      DEFAULT_LANG: en
      LOCALIZATION_FOLDER: /app/translations
      MAX_SHORT_URL: 10
      MAX_USAGES: 0
      MAX_RPM: 0
      MAX_RPD: 0
      VIRUSTOTAL_API_KEY: NoNoYouDontgetMyKeyXP
      PUBLIC_URL: https://s.aVeryGoodDomainName.ch
      ORIGIN: https://s.aVeryGoodDomainName.ch
    networks:
      - snapp_test
      - proxy

networks:
  snapp_test: # Snapp Network so Snapp and redis can communicate
    external: false
  proxy: # Proxy network for reverse proxy 
    external: true
```

And im also a bit confused about three of the env variables. What do these do?
- MAX_RPM
- MAX_RPD
- MAX_USAGES
___
About the open ports on Redis, since every docker compose stack automatically creates its own docker network, the port section is not needed (at least on Redis) and could be a potential security issue. It actually will be a security issue when no password!

Inside the docker network the ports are always available to other containers, but if you open the ports with `port:` you open them on the host and (at least with UFW) also completely ignore firewall rules you set up.

you can just use `redis-stack` for `DB_HOST` and comment out the ports ant it'l work just fine.

**Reply by urania-dev** [reply]
I'll give you a better answer, but basically yes, i espose the port on headscale vpn (so it is reachable by server but not clients not in the VPN) and password set. Of course. The basic test compose was written for the purpouse of the test :D 

The maxs are the rate limits. You can skip them and set them in admin panel if you want :)

You should also have the account still working on main snapp.li :)

**Reply by urania-dev** [reply]
Also, would It make sense a script that on launch searches for snapp<.7 db.sqlite for auto import of the snapps?

Not sure about this features as pushing latest would not be compatibile with pre .7 settings..

**Reply by Hutch79** [reply]
> I'll give you a better answer, but basically yes, i espose the port on headscale vpn (so it is reachable by server but not clients not in the VPN) and password set. Of course. The basic test compose was written for the purpouse of the test :D 

👍 
Off Topic question, But as a fresh NetBird user (2 weeks), do you have a UI for Headscale? And how easy is it to use a custom headscale server instead of the Tailscale SaaS?

> The maxs are the rate limits.

Ok, but what is RPM and RPD? ^^ I don't think that RPM is Rotations Per Minute is XD

> You should also have the account still working on main snapp.li :)

On Snapp.li yes, but not on my own test server ^^

> Also, would It make sense a script that on launch searches for snapp<.7 db.sqlite for auto import of the snapps?

At least for the full 0.7 release on the latest tag.
If you (and I admit, I rarely do) don't read the release notes and just pull latest, it would break a lot.

**Reply by urania-dev** [reply]
So!

Tailscale i found it really easy to use. It has headscale ui to check the status but it's basically mantained via cli. For what it's worth, when i set up headscale with docker + traefik all i need to do is curl the tailscale installer and use the link to my headscale server, and that's it. 

I tried Netbird, but failed to understand it. :)

RPM => Request Per Minute, 
RPD => Request Per Day

i would try expose the port to local ip (if homeserver) and test again. or try password + public port (that's dangerous you're right), just to check the ability  to communicate with the db. 

i will think about the script for autoimport on latest for the .7 , i was waiting to some user giving feedback, and since you're not managing to use it better understand what is not working and then setup new features :D

**Comment by urania-dev** [comment]
I updated 0.7.test version. now it checks on a sqlite db, so make sure to reference it in the docker compose and if available it shows Upgrade db in imports

```yml
version: "3"
services:
  redis:
    image: redis/redis-stack:latest
    # ports: # you can specify LOCAL_IP OR VPN_IP to make db or redis insight available privately
      # - (LOCAL_IP or VPN_IP):6379:6379/tcp
      # - (LOCAL_IP or VPN_IP):8001:8001
    volumes:
      # - /home/snapp/redis/test:/data:rw this make sure to enable persistance through docker restarts and shutdowns or updates
      - /etc/localtime:/etc/localtime:ro
    networks: 
      - snapp-stack
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes" # Optional: `--requirepass mypassword`

  snapp:
    image: uraniadev/snapp:0.7.test
    ports:
      - 5173:3000
    volumes:
      - /home/snapp/app/translations:/app/translations:ro
      - /home/snapp/redis/theme/theme.css:/app/static/custom-theme.css
    networks: 
      - snapp-stack
    environment:
      AUTH_SECRET: # random string, generate it with bash: openssl rand -base64 32
      DB_HOST: redis
      # DB_PASS: # Optional: Requires `--requirepass mypassword` in REDIS_ARGS
      DB_PORT: 6379
      DB_IDX: 0
      ENABLE_LIMITS: false
      ENABLE_SIGNUP: true
      ENABLE_HOME: false
      DEFAULT_THEME: dark 
      DEFAULT_LANG: en
      LOCALIZATION_FOLDER: /app/translations
      MAX_SHORT_URL: 10
      MAX_USAGES: 0
      MAX_RPM: 0
      MAX_RPD: 0
      UMAMI_WEBSITE_ID: 
      UMAMI_URL: 
      VIRUSTOTAL_API_KEY: 
      PUBLIC_URL: http://host:5173
      ORIGIN: http://host:5173


networks:
  snapp-stack: # Snapp Network so Snapp and redis can communicate
    external: false
  bridge: # Proxy network for reverse proxy 
    external: true
```

tried like this works.

i should have updated enough to works with a compose as simple as 

```yml
version: "3"
services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - /home/snapp/redis/data:rw #this make sure to enable persistance through docker restarts and shutdowns or updates
      - /etc/localtime:/etc/localtime:ro
    networks:
      - snapp-stack
    environment:
      REDIS_ARGS: "--save 60 1 --appendonly yes" # Optional: `--requirepass mypassword`

  snapp:
    image: uraniadev/snapp:0.7.test
    ports:
      - 3000:3000
    networks:
      - snapp-stack
    environment:
      AUTH_SECRET: # generate it with: openssl rand -base64 32
      DB_HOST: redis
      # Also you can omit this given you use it from http://localhost:3000
      # PUBLIC_URL: https://labs.snapp.li
      # ORIGIN: https://labs.snapp.li

networks:
  snapp-stack: # Snapp Network so Snapp and redis can communicate
    external: false
  
```
