### ISSUE TITLE
Default login?

### ISSUE THREAD

**Issue by firestrife23** [urania-dev/snapp#1]
I followed your instruction and created a Docker container, but I'm having trouble logging in because it says the administrator account already exists.

**Comment by urania-dev** [comment]
HA! it should not, i had made something wrong, then. 

Sorry, i will rebuild the image and re-upload double checking the db to be empty on creation. Also, are you using it in localhost?

**Comment by urania-dev** [comment]
should be fixed with new version of docker image.

**Comment by urania-dev** [comment]
I just noticed that I closed the comment by mistake, my first public and not entirely alone repository, sorry :)

**Comment by urania-dev** [comment]
No, it's just a simple panel with the own urls, it starts as a lazy private project. 
There is none, the db should be empty on startup, if can be helpful to mount volume a db.sqlite compliant with the prisma client is in static folder.

signups can be enabled with `ENABLE_MULTIUSER` set to `true`

**Comment by firestrife23** [comment]
I'm happy to share that it's working with Traefik. However, the Metric is displaying null instead of the real countries. Traefik sends the IP address through X-Forwarded-For.

**Comment by urania-dev** [comment]
Perfect i will close for the issue part,

for the real IP however i use traefik and receive the correct x-real-ip as equal to x-forwarded-for,

i'm using as an habit this security headers in my treafik configuration for my services. don't know if it is related. 

```
security-headers:
      headers:
        customResponseHeaders:
          X-Forwarded-Proto: 'https'
          X-Robots-Tag: 'none,noarchive,nosnippet,notranslate,noimageindex'
          server: ''
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: 'same-origin'
        hostsProxyHeaders:
          - 'X-Forwarded-Host'
        customRequestHeaders:
          X-Forwarded-Proto: 'https'
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
```
