### ISSUE TITLE
Error in `docker-compose.yml` on the app homepage

### ISSUE THREAD

**Issue by bobo2334** [urania-dev/snapp#22]
```yml
redis:
  volumes:
    - /home/snapp/redis/data:rw
```

should be `/home/snapp/redis:/data:rw`
