### ISSUE TITLE
Reload "F5" results in Page not available

### ISSUE THREAD

**Issue by Schnurp** [urania-dev/snapp#25]
Hi there,

I installed snapp in Docker on my Synology NAS with following .yaml:

```
version: '3'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: Snapp-REDIS
    # ports: # you can specify LOCAL_IP OR VPN_IP to make db or redis insight available privately
    # - (LOCAL_IP or VPN_IP):6379:6379/tcp
    # - (LOCAL_IP or VPN_IP):8001:8001
    volumes:
      - /volume1/docker/snapp/redis:/data:rw
      # this make sure to enable persistance through docker restarts
      # and shutdowns or updates -- change it to a folder of your choise
      - /etc/localtime:/etc/localtime:ro
   #networks:
   #   - snapp-stack
    environment:
      REDIS_ARGS: '--save 60 1 --appendonly yes' # Optional: `--requirepass mypassword`
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    restart: unless-stopped

  snapp:
    image: uraniadev/snapp:latest
    container_name: Snapp
    ports:
      - 6421:3000
    volumes:
      # provide origin json downloadable
      # from github if you intend to use it
      #
      # - /home/snapp/app/translations:/app/translations:ro 
      # - /home/snapp/redis/theme/theme.css:/app/static/custom-theme.css
      # See (Discussion about theming)[https://github.com/urania-dev/snapp/discussions/18]
      - /volume1/docker/snapp/app/translations:/app/translations:ro
      # - /volume1/docker/snapp/redis/theme/theme.css:/app/static/custom-theme.css
    depends_on:
     redis: 
      condition: service_healthy
    #networks:
    #  - snapp-stack
    environment:
      AUTH_SECRET: XXX
      DB_HOST: redis
      # DB_PASS: # Optional: Requires `--requirepass mypassword` in REDIS_ARGS
      DB_PORT: 6379
      # DB_IDX: 0
      ALLOW_UNSECURE_HTTP: true
      ENABLE_LIMITS: false
      ENABLE_SIGNUP: false
      ENABLE_HOME: true
      DEFAULT_THEME: dark
      DEFAULT_LANG: en
      LOCALIZATION_FOLDER: /app/translations
      # MAX_SHORT_URL: 10
      # MAX_USAGES: 0
      # MAX_RPM: 0
      # MAX_RPD: 0
      # UMAMI_WEBSITE_ID:
      # UMAMI_URL:
      # VIRUSTOTAL_API_KEY:
      PUBLIC_URL: https://url.web.de
      ORIGIN: https://url.web.de
      # NODE_ENV: production
      # NODE_ENV: development 
      TIMEZONE: Europe/Berlin
      SMTP_HOST: abc.de
      SMTP_USER: 
      SMTP_PASSWORD: 
      SMTP_FROM: a@b.de

networks:
  #snapp-stack: # Snapp Network so Snapp and redis can communicate but redis is isolated from the wan
  #external: false
    default:
       external:
          name: Diverses
```

Now I have the following issue. I start the project on my NAS. Everything starts up fine. It runs with a reverse proxy so that I can connect from external. If I press F5 on the page it cant load the page anymore until I delete the Cookies. 

If Home is disabled it is more difficult to get back at all. 

I even tried reverse proxy with http instead of https and also tried different port settings. nothing helps.

Can anyone help me with that problem?

**Comment by urania-dev** [comment]
Weird indeed, i'll try to look into it

**Comment by Schnurp** [comment]
> Weird indeed, i'll try to look into it

Let me know how I can help / assist you or test things out.

I also recognized that this error only shows up on the Dashboard or Home (if Home is disabled) and Admin Panel not on Users, Metrics and Settings.

**Comment by Schnurp** [comment]
> Do the dockers leave any dock regarding this issue? Like missing cookies or settings from cookie?

Nothing I am aware of. I have 4 Cookies from Snapp: snap:theme, __Secure-authjs.session-token, __Secure-authjs.callback-url, __Host-authjs.csrf-token

**Comment by urania-dev** [comment]
> Do the dockers leave any **LOGS** regarding this issue? Like missing cookies or settings from cookie?

that word was log, my fault. I tried to check the cookies interaction here and there on the app, and it should work even without cause it doesn't rely on them and it has defaul set for alternative, as long as we are talking about the two i use (theme and lang) the third one (AUTHJS) are the cookies related to authentication, so i think that's the real problem, but without a log or similar it is difficult to understand what is going wrong. 

App docker still on
```
Listening on 0.0.0.0:3000
```

with anything else?

**Comment by Schnurp** [comment]
> Listening on 0.0.0.0:3000

This is the only line on the Snapp Container log.

This ist the Snapp-Redis Logfile:

`date	stream	content
2024/05/26 09:34:02	stdout	8:M 26 May 2024 09:34:02.179 * Background saving terminated with success
2024/05/26 09:34:02	stdout	81:C 26 May 2024 09:34:02.079 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
2024/05/26 09:34:02	stdout	81:C 26 May 2024 09:34:02.075 * DB saved on disk
2024/05/26 09:34:00	stdout	8:M 26 May 2024 09:34:00.872 * Background saving started by pid 81
2024/05/26 09:34:00	stdout	8:M 26 May 2024 09:34:00.872 * 1 changes in 60 seconds. Saving...
2024/05/26 09:31:05	stdout	8:M 26 May 2024 09:31:05.003 * Background saving terminated with success
2024/05/26 09:31:04	stdout	43:C 26 May 2024 09:31:04.943 * Fork CoW for RDB: current 1 MB, peak 1 MB, average 1 MB
2024/05/26 09:31:04	stdout	43:C 26 May 2024 09:31:04.941 * DB saved on disk
2024/05/26 09:31:04	stdout	8:M 26 May 2024 09:31:04.098 * Background saving started by pid 43
2024/05/26 09:31:04	stdout	8:M 26 May 2024 09:31:04.096 * 1 changes in 60 seconds. Saving...
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.252 * <module> Scanning index usages:index in background: done (scanned=32)
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.251 * <module> Scanning index usages:index in background
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.251 * <module> Scanning index snapps:index in background: done (scanned=32)
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.250 * <module> Scanning index snapps:index in background
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.250 * <module> Scanning index apikey:index in background: done (scanned=32)
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.250 * <module> Scanning index apikey:index in background
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * Ready to accept connections tcp
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * Opening AOF incr file appendonly.aof.1.incr.aof on server start
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * DB loaded from append only file: 0.629 seconds
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * <redisgears_2> Loading finished, re-enable key space notificaitons.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * <search> Loading event ends
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 # <search> Skip background reindex scan, redis version contains loaded event.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:05.249 * DB loaded from incr file appendonly.aof.1.incr.aof: 0.629 seconds
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * DB loaded from base file appendonly.aof.1.base.rdb: 0.000 seconds
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * Done loading RDB, keys loaded: 0, keys expired: 0.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * RDB is base AOF
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * RDB memory usage when created 1.14 Mb
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * RDB age 44617 seconds
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * Loading RDB produced by version 7.2.4
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * Reading RDB base file on AOF loading...
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * <redisgears_2> Got a loading start event, clear the entire functions data.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.620 * <search> Loading event starts
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.619 * Server initialized
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.618 * Module 'redisgears_2' loaded from /opt/redis-stack/lib/redisgears.so
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.588 * <redisgears_2> Registered backend: js.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.447 * <redisgears_2> RedisGears v2.0.20, sha='9b737886bf825fe29ddc2f8da81f73cbe0b4e858', build_type='release', built_for='Linux-ubuntu22.04.x86_64', redis_version:'7.2.4', enterprise:'false'.
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.447 * <redisgears_2> Failed loading RedisAI API.
2024/05/26 09:30:05	stdout	
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.447 # <redisgears_2> could not initialize RedisAI_InitError
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.447 * <redisgears_2> Detected redis oss
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.445 * <redisgears_2> Created new data type 'GearsType'
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.405 * Module 'bf' loaded from /opt/redis-stack/lib/redisbloom.so
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.405 * <bf> RedisBloom version 2.6.12 (Git=unknown)
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.392 * <search> Acquired RedisJSON_V5 API
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.392 * Module 'ReJSON' loaded from /opt/redis-stack/lib/rejson.so
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Enabled diskless replication
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Exported RedisJSON_V5 API
2024/05/26 09:30:05	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Exported RedisJSON_V4 API
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Exported RedisJSON_V3 API
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Exported RedisJSON_V2 API
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Exported RedisJSON_V1 API
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> version: 20610 git sha: unknown branch: unknown
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.392 * <ReJSON> Created new data type 'ReJSON-RL'
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * Module 'timeseries' loaded from /opt/redis-stack/lib/redistimeseries.so
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> Detected redis oss
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> Setting default series ENCODING to: compressed
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> loaded server DUPLICATE_POLICY: block
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> loaded default CHUNK_SIZE_BYTES policy: 4096
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> Redis version found by RedisTimeSeries : 7.2.4 - oss
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.307 * <timeseries> RedisTimeSeries version 11012, git_sha=81d5ef59cdaba059a0eb9705c3c4b0127949f388
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.128 * Module 'search' loaded from /opt/redis-stack/lib/redisearch.so
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> Enabled role change notification
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> Initialized thread pools!
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  10000, search pool size: 20, index pool size: 8, 
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> Low level api version 1 initialized successfully
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> RediSearch version 2.8.13 (Git=2.8-c1535c6)
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:04.127 * <search> Redis version found by RedisSearch : 7.2.4 - oss
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:03.978 * Module 'RedisCompat' loaded from /opt/redis-stack/lib/rediscompat.so
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:03.727 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:03.727 * Running mode=standalone, port=6379.
2024/05/26 09:30:04	stdout	8:M 26 May 2024 09:30:03.726 * monotonic clock: POSIX clock_gettime
2024/05/26 09:30:04	stdout	8:C 26 May 2024 09:30:03.725 * Configuration loaded
2024/05/26 09:30:04	stdout	8:C 26 May 2024 09:30:03.725 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=8, just started
2024/05/26 09:30:04	stdout	8:C 26 May 2024 09:30:03.725 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2024/05/26 09:30:03	stdout	8:C 26 May 2024 09:30:03.725 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

**Comment by urania-dev** [comment]
Do you think you can run a test version where i try to output more logs in order to address your specifico problem?

**Comment by Schnurp** [comment]
Yes I try.

**Comment by urania-dev** [comment]
uraniadev/snapp:0.7.3.test

here it is, uploded, let me know if it tells something better

**Comment by Schnurp** [comment]
Here comes my logfile. 
[2024-05-26 11-40-28 Snapp.pdf](https://github.com/urania-dev/snapp/files/15446952/2024-05-26.11-40-28.Snapp.pdf)

**Comment by urania-dev** [comment]
no i think we have the culprit. it seems it doesn't find the stargazer count (the stars count on github), i try to fix it and reupload a test2, let's see what happens. sorry to bother you with this try and catch.
it tries to get the count also if the page is disabled, that should not give error, but nonetheless it is an info not needed elswehere, so i'm changing the process in order to exclude github call if not needed, and that's already an improvement. 

by the way can you look in redis if the key settings:repo:info get set?

**Comment by Schnurp** [comment]
No problem, if we can localize the problem and fix it, it's worth it.

Many thanks for the information.

I will now apply the new image.

What exactly do you want to know from Redis and where can I find the information you need?

**Comment by urania-dev** [comment]
![immagine](https://github.com/urania-dev/snapp/assets/153094889/0800d186-96c3-468e-a302-191d9a86f2b5)

**Comment by urania-dev** [comment]
i don't have synolgy but can it be that the call vs github get shut down as it is a third party url not in origin list? (or something like that?)

**Comment by urania-dev** [comment]
sorry there's been some mixup between answers and updates to already present posts, i set the test-2 image, and linked a screen on how to reach redis stack gui for looking at the key i mentioned

**Comment by Schnurp** [comment]
> i don't have synolgy but can it be that the call vs github get shut down as it is a third party url not in origin list? (or something like that?)

not that I know...

**Comment by Schnurp** [comment]
> sorry there's been some mixup between answers and updates to already present posts, i set the test-2 image, and linked a screen on how to reach redis stack gui for looking at the key i mentioned

test-2 same error. Less Info in Protocol. Still Dashboard and Admin Panel not reloadable.

I don´t know how to get to that redis page you posted.

**Comment by urania-dev** [comment]
the redirect is due to the necessities of authentication, i will remove the extended log and check to let the app due its deeds.

the page of redis is available unquoting 

  # ports: # you can specify LOCAL_IP OR VPN_IP to make db or redis insight available privately
    # - (LOCAL_IP or VPN_IP):8001:8001

in compose of redis stack


-- 

btw> uraniadev/snapp:0.7.3-test-3

**Comment by Schnurp** [comment]
still the same problem...

trying to get redisinsight working...

**Comment by urania-dev** [comment]
I re read your compose and you are removing internal connection between db and app, try allow snapp network
```
version: '3'
services:
  redis:
    image: redis/redis-stack:latest
    container_name: Snapp-REDIS
    ports:
    # - 6379:6379/tcp
    - 8001:8001
    volumes:
      - /volume1/docker/snapp/redis:/data:rw
      # this make sure to enable persistance through docker restarts
      # and shutdowns or updates -- change it to a folder of your choise
      - /etc/localtime:/etc/localtime:ro
   networks:
      - snapp-stack
    environment:
      REDIS_ARGS: '--save 60 1 --appendonly yes' # Optional: `--requirepass mypassword`
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    restart: unless-stopped

  snapp:
    image: uraniadev/snapp:latest
    container_name: Snapp
    ports:
      - 6421:3000
    volumes:
      # provide origin json downloadable
      # from github if you intend to use it
      #
      # - /home/snapp/app/translations:/app/translations:ro 
      # - /home/snapp/redis/theme/theme.css:/app/static/custom-theme.css
      # See (Discussion about theming)[https://github.com/urania-dev/snapp/discussions/18]
      - /volume1/docker/snapp/app/translations:/app/translations:ro
      # - /volume1/docker/snapp/redis/theme/theme.css:/app/static/custom-theme.css
    depends_on:
     redis: 
      condition: service_healthy
    networks:
      - snapp-stack
    environment:
      AUTH_SECRET: XXX
      DB_HOST: redis
      # DB_PASS: # Optional: Requires `--requirepass mypassword` in REDIS_ARGS
      DB_PORT: 6379
      # DB_IDX: 0
      ALLOW_UNSECURE_HTTP: true
      ENABLE_LIMITS: false
      ENABLE_SIGNUP: false
      ENABLE_HOME: true
      DEFAULT_THEME: dark
      DEFAULT_LANG: en
      LOCALIZATION_FOLDER: /app/translations
      # MAX_SHORT_URL: 10
      # MAX_USAGES: 0
      # MAX_RPM: 0
      # MAX_RPD: 0
      # UMAMI_WEBSITE_ID:
      # UMAMI_URL:
      # VIRUSTOTAL_API_KEY:
      PUBLIC_URL: https://url.web.de
      ORIGIN: https://url.web.de
      # NODE_ENV: production
      # NODE_ENV: development 
      TIMEZONE: Europe/Berlin
      SMTP_HOST: abc.de
      SMTP_USER: 
      SMTP_PASSWORD: 
      SMTP_FROM: a@b.de

networks:
  snapp-stack: 
      external: false
  default:
       external:
          name: Diverses
```
