### ISSUE TITLE
env variables for a custom admin account are being ignored on sqlite

### ISSUE THREAD

**Issue by schuesslerma** [urania-dev/snapp#35]
## Feature
Configuration of the admin user via env variables

### Environment
Docker container with image uraniadev/snapp:0.8.1
Utilizing the default database configuration (sqlite)

## Steps to reproduce
1. Deploy a docker container with docker compose:
    ```
    services:
      snapp:
        image: uraniadev/snapp:0.8.1
        ports: 
          - 3000:3000
        environment:
          ORIGIN: https://my.custom.url
          TOKEN_SECRET: bXlfY3VzdG9tX3Rva2VuX3NlY3JldA==
          ADMIN_USERNAME: mycustomuser
          ADMIN_PASSWORD: mycustompassword
    ```

2. Open the web app and proceed to the login
3. Enter the specified credentials
   - Username: mycustomuser
   - Password: mycustompassword
4. Click 'Sign in' / press enter

## Expected Result
The login is successful

### Actual Result
The login fails with a message of 'User not found.'

## Workarround
Delete the database **db.sqlite** in **/app/prisma/sqlite** and restart the container.
This leads to the recreation of said database and an effective run of the migration.
Now the custom admin user is correctly configured.

### Sideffects
Unknown
