### ISSUE TITLE
Composer file with volume mount for db.sqlite

### ISSUE THREAD

**Issue by acseven** [urania-dev/snapp#50]
Hi,

I'm trying to try out snapp but I'm having issues with logging in, and it seems that the database isn't getting populated with data, I can't seem to find what I'm doing wrong here. 

Here's what I have in the composer file (Portainer):

```
version: '3.9'
services:
  snapp-url-short:
   image: uraniadev/snapp:latest
   ports:
    - 43000:3000
   volumes:
     - /docker/tools-prod-snapp-url-short/v/db/db.sqlite:/app/prisma/db.sqlite
   environment:
    NODE_ENV: development
    DATABASE_URL: "file:./db.sqlite"
    DATABASE_PROVIDER: sqlite # mysql | sqlite | pg
    TOKEN_SECRET: [>REDACTED<] # openssl rand -base64 32
    ORIGIN: https://url.[>REDACTED<]
    TIMEZONE: Europe/London

    #DATABASE_POSTGRES_URL= # "postgresql://root:password@postgres:5432/snappdb"
    #DATABASE_MYSQL_URL= # "mysql://root:password@mariadb:3306/snappdb"
    
    ADMIN_USERNAME: [>REDACTED<] # must be specified on first launch as it initiate the database
    ADMIN_EMAIL: [>REDACTED<] # must be specified on first launch as it initiate the database
    ADMIN_PASSWORD: [>REDACTED<] # must be specified on first launch as it initiate the database
    PORT: 3000 # app port
    #PUBLIC_UMAMI_WEBSITE_ID: # uuid  #https://github.com/umami-software/umami
    #PUBLIC_UMAMI_WEBSITE_URL: # https://umami.example.com/script.js
    DISABLE_HOME: false
    ENABLE_SIGNUP: false
    VTAPI_KEY: [>REDACTED<] # VIRUSTOTAL API KEY
    SMTP_HOST: [>REDACTED<] # host smtp.example.com
    SMTP_USER: [>REDACTED<] # info@example.com
    SMTP_PASS: "[>REDACTED<]" # account password
    SMTP_FROM: [>REDACTED<] # no-reply@example.com
    SMTP_PORT: 465 # 465
    SMTP_SSL: true # true
```

I've created an empty `db.sqlite` file on the volume location. 

The logs state:

```
Prisma schema loaded from prisma/sqlite/schema.prisma
✔ Generated Prisma Client (v5.18.0) to ./node_modules/@prisma/client in 326ms
Start by importing your Prisma Client (See: http://pris.ly/d/importing-client)
Tip: Want to react to database changes in your app as they happen? Discover how with Pulse: https://pris.ly/tip-1-pulse
npm notice
npm notice New minor version of npm available! 10.8.2 -> 10.9.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.9.0
npm notice To update run: npm install -g npm@10.9.0
npm notice
Prisma schema loaded from prisma/sqlite/schema.prisma
Datasource "db": SQLite database "db.sqlite" at "file:./db.sqlite"
1 migration found in prisma/migrations
No pending migrations to apply.
-------------------------------------------
             Welcome to Snapp!
-------------------------------------------
      Thank you for choosing this app.
      Have a great day and enjoy your
            experience with us!
-------------------------------------------
Listening on 0.0.0.0:3000
```

While trying to login the console reads:

`Failed to load resource: the server responded with a status of 403 (Forbidden)`

What could be wrong here?
