### ISSUE TITLE
Login dont work 

### ISSUE THREAD

**Issue by Jonaswitze** [urania-dev/snapp#66]
Hi, 
when I try to log in with both the admin account and a created account, nothing happens. There is no error in the browser or in docker.

**Comment by urania-dev** [comment]
> Hi, 
> when I try to log in with both the admin account and a created account, nothing happens. There is no error in the browser or in docker.

Would you share the configuration used?

**Comment by Jonaswitze** [comment]
```
services:
  snapp:
    image: uraniadev/snapp:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: 'file:./db.sqlite'
      DATABASE_PROVIDER: sqlite # mysql | sqlite | postgres
      TOKEN_SECRET: ***
      SMTP_HOST: ***
      SMTP_USER: ***
      SMTP_PASS: ***
      SMTP_FROM: ***
      SMTP_PORT: 465
      SMTP_SSL: true
      ENABLE_SIGNUP: true
      ORIGIN: http://10.0.20.4:3000
```
