### ISSUE TITLE
Change to instructions to point out default login

### ISSUE THREAD

**Issue by bryceprutsos** [urania-dev/snapp#7]
Hello, I've successfully deployed your container using Dockge (https://github.com/louislam/dockge). The deployment went smoothly, and I've also configured it with a reverse proxy, which appears to be functioning well. However, I'm unsure about the default login credentials. I checked your closed issues but couldn't find the information there either. It might be helpful to include this detail on the default page. I'm genuinely interested in your project and am willing to assist with testing whenever I have the time.

**Comment by urania-dev** [comment]
There are none! :)

It should allows to register the first account, and then it stops new sign up if env multi-user is false

**Comment by Brukkil** [comment]
Hi @urania-dev 

I've used two approaches but no one helps

```yaml
version: "3"
services: 
 snappli-private:
    restart: always
    container_name: snappli-private
    user: root
    ports:
      - "5051:3000"
    image: "uraniadev/snapp:latest"
    volumes:
    - ./db/:/app/prisma/
    environment:
      PUBLIC_URL: http://dkr
      ORIGIN: http://dkr
```

In this case i'm getting such issue and empty file in db folder
```log
snappli-private  | 🖥️  Starting handle server side
snappli-private  | 🕐 Setting up Scheduled Jobs
snappli-private  | --- 🧹 Cleaning (0) Scheduled Jobs already set.
snappli-private  | --- ✔️  (1) Jobs Scheduled
snappli-private  | Listening on 0.0.0.0:3000
snappli-private  | PrismaClientKnownRequestError: 
snappli-private  | Invalid `prisma.settings.findFirst()` invocation:
snappli-private  | 
snappli-private  | 
snappli-private  | The table `main.Settings` does not exist in the current database.
snappli-private  |     at ni.handleRequestError (/app/node_modules/@prisma/client/runtime/library.js:124:6817)
snappli-private  |     at ni.handleAndLogRequestError (/app/node_modules/@prisma/client/runtime/library.js:124:6206)
snappli-private  |     at ni.request (/app/node_modules/@prisma/client/runtime/library.js:124:5926)
snappli-private  |     at async l (/app/node_modules/@prisma/client/runtime/library.js:129:10023)
snappli-private  |     at async load (file:///app/build/server/chunks/0-4e2005a2.js:7:17)
snappli-private  |     at async load_server_data (file:///app/build/server/index.js:2369:18)
snappli-private  |     at async file:///app/build/server/index.js:3801:18 {
snappli-private  |   code: 'P2021',
snappli-private  |   clientVersion: '5.6.0',
snappli-private  |   meta: { table: 'main.Settings' }
snappli-private  | }
```

Also, I've tried without specifying a volume so the app has full control of files inside the container and can create a db file. When it happens - I'm able to open the page in a browser, but can't sign up so I can't log in and use the app.

I'll be happy if you can advise how to fix that

**Comment by urania-dev** [comment]
Hello, yes, it doesn't install a new db if missing, or if linked as a volume. i'll fix the error soon, but meanwhile you can download and set the correct format of the db with the example db in [/static/db.sqlite](https://github.com/urania-dev/snapp/blob/main/static/db.sqlite). this way should work without issues.

:)

**Comment by urania-dev** [comment]
With latest version in push the prisma scheme onto the db on startup, so it would render any linked sqlite db valid. :)

**Comment by Brukkil** [comment]
Sorry for reopening this issue
Just want to focus on the main topic of the issue - the registration button does not work
It just looks like the button which not pressing. No alerts, no logs, nothing. The same with the login.

**Comment by urania-dev** [comment]
No problem, let's understand what is not working. should you have logs in docker container have you posted it?
the DB file is being found? Are you using a docker volume for it?

:)

**Comment by Brukkil** [comment]
So firstly - all logs after copying the db file from static is 
```log
Attaching to snappli-private
snappli-private  | 🖥️  Starting handle server side
snappli-private  | 🕐 Setting up Scheduled Jobs
snappli-private  | --- 🧹 Cleaning (0) Scheduled Jobs already set.
snappli-private  | --- ✔️  (1) Jobs Scheduled
snappli-private  | Listening on 0.0.0.0:3000
```
After that i'm trying to create a user by this page */auth/signup*

Just for better understanding
docker-compose.yaml
```yaml
version: "3"
services: 
 snappli-private:
    restart: always
    container_name: snappli-private
    user: root
    ports:
      - "5051:3000"
    image: "uraniadev/snapp:latest"
    volumes:
    - ./db/:/app/prisma/
    environment:
      PUBLIC_URL: http://dkr
      ORIGIN: http://dkr
      ENABLE_MULTIUSER: true
```

And there are logs from the browser console
```log
POST http://dkr:5051/auth/signup 403 (Forbidden)
window.fetch @ start.22344c0b.js:1
u            @ forms.06e89f4e.js:1
```

**Comment by urania-dev** [comment]
Wait i think looking at your docker compose you end up overwriting prisma.scheme with an empty file unless you cloned the repo.

To link actual db to docker instance it necessary to point at the db.sqlite file not at the folder.

# '/home/snapp/db.sqlite:/app/prisma/db.sqlite'

more over i created an automation on startup where if a ADMIN_USERNAME and ADMIN_PASSWORD are set it will try to create them on startup. If not already existing.

Let me know if it works for you now! :)

**Comment by urania-dev** [comment]
Also noticing that you are using a localhost (at least assuming http://dkr is the real deal) so you should also use -e NODE_ENV=development  as it is not through secure HTTPS

**Comment by Brukkil** [comment]
Now it works with this docker-compose
```yaml
version: "3"
services: 
 snappli-private:
    restart: always
    container_name: snappli-private
    user: root
    ports:
      - "5051:3000"
    image: "uraniadev/snapp:latest"
    volumes:
      - ./db/:/app/prisma/
    environment:
      PUBLIC_URL: http://dkr:5051
      ORIGIN: http://dkr:5051
      ENABLE_MULTIUSER: true
      NODE_ENV: development
```

Thank you for your effort!
