### ISSUE TITLE
Graceful handling of database unavailability

### ISSUE THREAD

**Issue by acseven** [urania-dev/snapp#82]
When using an external database, if it it's not available or stops being available to snapp, the container just crashes and that can only be repaired or monitored by keeping up with the docker host. 

If possible, it would be great to have some graceful handling of database unavailability, both on starting the container but mainly while it's running. Maybe something like:

1. If running and the database connection is lost, use current email settings to send an alert, and keep the application in a suspended state waiting for the db connection to be re-established. 
2. If starting up and the database connection enter a loop process to try and connect to the database (this would be in case servers are coming back up on their unattended). 
3. prior settings controlled by ENV variables.

Regards!

**Comment by acseven** [comment]
For reference, I'm using something like this to kind of handle these issues, but it would be nice to have it in the app itself:

```
services:

  wait-for-server:
    image: busybox
    command: /bin/sh -c "until nc -z -v -w30 databasehost.local 5432; do echo 'Waiting for server...'; sleep 5; done; echo 'Database is up!'"
    restart: "no"  # This service only runs until the database is available, no need for restart
    networks:
      - snapp

  snapp:
    image: uraniadev/snapp:latest
    ports:
      - 3000:3000
    environment:
      DATABASE_POSTGRES_URL: "postgresql://postgres:password@databasehost.local:5432/snappdb"
      TOKEN_SECRET: # openssl rand -base64 32
      ORIGIN: https://snapp.domain.com
      DATABASE_PROVIDER: postgres
    depends_on:
      - wait-for-server  # Ensure the database server is reachable first
    networks:
      - snapp
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "snapp.domain.com"]  # Replace with the actual health check URL
      interval: 30s  # Check every 30 seconds
      retries: 0      # 0 = infinite
      start_period: 10s  # Wait 10 seconds after container starts before starting health checks
      timeout: 5s      # Timeout after 5 seconds if no response

networks:
  snapp:
    external: false
```
