### ISSUE TITLE
Error: connect ECONNREFUSED (host):23100

### ISSUE THREAD

**Issue by acseven** [urania-dev/snapp#84]
All my urls stopped working without any noticeable reason, no changes made. 

The error in the docker logs states:

```
TypeError: fetch failed

    at node:internal/deps/undici/undici:13484:13

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

  [cause]: Error: connect ECONNREFUSED 192.168.3.14:23100

      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {

    errno: -111,

    code: 'ECONNREFUSED',

    syscall: 'connect',

    address: '192.168.3.14',

    port: 23100

  }

}
```

**Comment by urania-dev** [comment]
Looks like the ip is not accessible, maybe the LAN address changed from env vars? 

I have very little info

**Comment by acseven** [comment]
This IP address '192.168.3.14' is the docker host where snapp is running. 


Here's my docker compose, and it wasn't changed in any way!

```
services:
  wait-for-server:
    image: busybox
    command: /bin/sh -c "until nc -z -v -w30 192.168.3.10 2665; do echo 'Waiting for server...'; sleep 5; done; echo 'Database is up!'"
    restart: "no"  # This service only runs until the database is available, no need for restart
    stop_grace_period: 10s  # Grace period before Docker kills the container.

  main:
   image: uraniadev/snapp:latest
   restart: always
   ports:
    - 43000:3000
   environment:
    TOKEN_SECRET: REDACTED
    ORIGIN: https://url.REDACTED.com
    TIMEZONE: Europe/Lisbon

    DATABASE_POSTGRES_URL: "postgresql://dbuser1:REDACTED@192.168.3.10:2665/tools_snapp_01"
    DATABASE_PROVIDER: postgres # mysql | sqlite | pg
    
    ADMIN_USERNAME: REDACTED
    ADMIN_EMAIL: REDACTED
    ADMIN_PASSWORD: REDACTED
    
    PORT: 3000 # app port
    DISABLE_HOME: true
    ENABLE_SIGNUP: false
    VTAPI_KEY: REDACTED # VIRUSTOTAL API KEY
    SMTP_HOST: REDACTED # host smtp.example.com
    SMTP_USER: REDACTED # info@example.com
    SMTP_PASS: REDACTED # account password
    SMTP_FROM: REDACTED # no-reply@example.com
    SMTP_PORT: 587 # 465
    SMTP_SSL: false # needs to be false if 587
   depends_on:
     - wait-for-server  # Ensure the database server is reachable first
   healthcheck:
     #test: ["CMD", "curl", "-f", "https://url.REDACTED.com"]  # Check if the public URL is reachable
     test: ["CMD", "wget", "--spider", "-q", "https://url.REDACTED.com"]  # Replace with the actual health check URL
     interval: 30s  # Check every 30 seconds
     retries: 0      # 0 = infinite
     start_period: 10s  # Wait 10 seconds after container starts before starting health checks
     timeout: 5s      # Timeout after 5 seconds if no response
   
```


Logs:

```
Prisma schema loaded from prisma/postgres/schema.prisma

✔ Generated Prisma Client (v6.1.0) to ./node_modules/@prisma/client in 71ms

Start by importing your Prisma Client (See: https://pris.ly/d/importing-client)

Tip: Curious about the SQL queries Prisma ORM generates? Optimize helps you enhance your visibility: https://pris.ly/tip-2-optimize

npm notice

npm notice New major version of npm available! 10.9.0 -> 11.1.0

npm notice Changelog: https://github.com/npm/cli/releases/tag/v11.1.0

npm notice To update run: npm install -g npm@11.1.0

npm notice

Prisma schema loaded from prisma/postgres/schema.prisma

Datasource "db": PostgreSQL database "tools_snapp_01" at "192.168.3.10:2665"

2 migrations found in prisma/migrations

No pending migrations to apply.

-------------------------------------------

             Welcome to Snapp!

-------------------------------------------

      Thank you for choosing this app.

      Have a great day and enjoy your

            experience with us!

-------------------------------------------

Listening on http://0.0.0.0:3000

TypeError: fetch failed

    at node:internal/deps/undici/undici:13484:13

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

  [cause]: Error: connect ECONNREFUSED 192.168.3.14:23100

      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {

    errno: -111,

    code: 'ECONNREFUSED',

    syscall: 'connect',

    address: '192.168.3.14',

    port: 23100

  }

}

TypeError: fetch failed

    at node:internal/deps/undici/undici:13484:13

    at process.processTicksAndRejections (node:internal/process/task_queues:105:5) {

  [cause]: Error: connect ECONNREFUSED 192.168.3.14:23100

      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {

    errno: -111,

    code: 'ECONNREFUSED',

    syscall: 'connect',

    address: '192.168.3.14',

    port: 23100

  }

}

```
