### ISSUE TITLE
Snapp x Coolify

### ISSUE THREAD

**Issue by Zai** [urania-dev/snapp#86]
Here is a docker compose working with Coolify.
I let you create a pull request on Coolify project, I think it will be better if it's come from you. ;)

```docker
services:
  snapp:
    image: 'uraniadev/snapp:latest'
    environment:
      - SERVICE_FQDN_SNAPP_3000
      - ORIGIN=$SERVICE_FQDN_SNAPP
      - DATABASE_PROVIDER=postgres
      - DATABASE_POSTGRES_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB
      - TOKEN_SECRET=$SERVICE_PASSWORD_SNAPP
      - ADMIN_USERNAME=${SNAPP_ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${SNAPP_ADMIN_PASSWORD:-password}
      - ADMIN_EMAIL=${SNAPP_ADMIN_EMAIL:?}
      - DISABLE_HOME=false
      - ENABLE_SIGNUP=false
      - PORT=3000
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: 'wget --no-verbose --tries=1 --spider http://0.0.0.0:3000 || exit 1'
      interval: 5s
      timeout: 20s
      retries: 10
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-snapp}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10

```

**Comment by urania-dev** [comment]
as i really appreciate your work, i'm actually working on next version that has priority as i don't have much time to dedicate to the project (not as much as i would), but i'm happy to do this too once the next version will be release (we are close to version 1 :) )

thank you again and i'll let you know more soon!

**Comment by urania-dev** [comment]
once the 0.9-rc version get fixed and tested i'll look into this :)

**Comment by Zai** [comment]
I just completed a fresh install of version `uraniadev/snapp:0.9-rc-004` on Coolify.

I will share it in a few days, giving me time to test for bugs

**Comment by Zai** [comment]
`docker-compose` working with `uraniadev/snapp:0.9-rc-009` on `Coolify`

```
services:
  snapp:
    image: 'uraniadev/snapp:0.9-rc-009'
    environment:
      - SERVICE_FQDN_SNAPP_3000
      - PUBLIC_URL=$SERVICE_FQDN_SNAPP
      - ORIGIN=$SERVICE_FQDN_SNAPP
      - DATABASE_PROVIDER=postgres
      - 'DATABASE_URL=postgres://$SERVICE_USER_POSTGRES:$SERVICE_PASSWORD_POSTGRES@postgresql:5432/$POSTGRES_DB'
      - TOKEN_SECRET=$SERVICE_PASSWORD_SNAPP
      - 'ADMIN_USERNAME=${SNAPP_ADMIN_USERNAME:?}'
      - 'ADMIN_EMAIL=${SNAPP_ADMIN_EMAIL:?}'
      - 'ADMIN_PASSWORD=${SNAPP_ADMIN_PASSWORD:?}'
      - DISABLE_HOME=false
      - ENABLE_SIGNUP=true
      - PORT=3000
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://0.0.0.0:3000/health'
      interval: 5s
      timeout: 20s
      retries: 10
  postgresql:
    image: 'postgres:16-alpine'
    volumes:
      - 'postgresql-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=$SERVICE_USER_POSTGRES
      - POSTGRES_PASSWORD=$SERVICE_PASSWORD_POSTGRES
      - 'POSTGRES_DB=${POSTGRES_DB:-snapp}'
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
      interval: 5s
      timeout: 20s
      retries: 10
```
